feat: add prettyNum utility
hugsmidjan/qj pull request #4
Opened 2020-09-02 22:38 UTC by Valur

2020-09-03 09:48 UTC, maranomynet requested changes
Geggjuð byrjun.
Call signature-ið þarf future-proofing, og default hegðunin þarf að vera aðeins önnur IMO.

2020-09-03 09:48 UTC, maranomynet commented on src/utils/prettyNum.tests.ts
> +});
😍 😍 😍 😍  ... I ❤️ tests.

2020-09-03 09:48 UTC, maranomynet commented on src/utils/prettyNum.tests.ts
> +		o(prettyNum(123456789)).equals('123.456.789');
Hvað er minnst surprising default hegðunin?

Er það íslenskt/skandínavískt formatting eða enskt?  (Ég myndi segja enskt.)

Einnig: Hvað á að gerast by default þegar ég sendi inn float?

```suggestion
		o(prettyNum(123456789)).equals('123,456,789');
		o(prettyNum(1234.56789)).equals('1,234.56789'); // <-- þetta?
		o(prettyNum(1234.56789)).equals('1,234.57'); // <-- eða þetta?
		o(prettyNum(1234567.89)).equals('1,235'); // <-- eða þetta?
```

Vænta hegðun í svona tilfellum þarf að negla í testi.

2020-09-03 09:48 UTC, maranomynet commented on src/utils/prettyNum.tests.ts
> +		o(prettyNum(123456.789, 2, '', '')).equals('12345679');
OK, þetta er bara skrýtið. 😄 
Decimal splitter táknið á aldrei að geta verið `''`. Annars er fallið að skila ólæsilegu/röngu úttaki.

Defaultaðu alltaf á punkt - ef ekkert annað er í boði.

```suggestion
		o(prettyNum(123456.789, 2, '', '')).equals('123456.79');
```

2020-09-03 09:48 UTC, maranomynet commented on src/utils/prettyNum.tests.ts
> +	o('Escapes strings', () => {
```suggestion
o.spec('prettyNum', () => {
	o('Pretty-prints numbers', () => {
```

2020-09-03 09:48 UTC, maranomynet commented on src/utils/prettyNum.tests.ts
> +	});
BTW, það vantar alveg að testa tölur sem eru minni en 1
```suggestion
		o(prettyNum(-1234.56)).equals('-1,234.57');
		o(prettyNum(-0.12)).equals('-0.12');
	});
```

...etc. með fyrirvara um default höndlun á tugabrotum.

2020-09-03 09:48 UTC, maranomynet commented on src/utils/prettyNum.ts
> +export const prettyNum = (number = 0, decimals = 0, tSep = '.', dSep = ',') => {
Mig myndi langa til að bæta við fleiri options síðar meir - t.d. `lang` og `leading zero` (`".5"` vs. `"0.5"`) og kannski fixed decimals (`"1.00"`).

...og þá fer svona flatur arguments listi alveg í rugl.

Þetta þarf strax að verða `opts` object.

```suggestion
// TODO: Add more...
const i18n = {
	is: [',', '.'],
	en: ['.', ','],
} as const;
type SupportedLanguages = keyof typeof i18n;

export type PrettyNumOptions = {
	/** Max number of decimals to render */
	decimals?: number;
	/** Should decimals be uniformly applied to all numbers */
	fixedDecimals?: boolean;
	/** If your language isn't supported use the `splitters` option instead. */
	lang?: SupportedLanguages;
	/** The tokens to use for a) decimals and b) thousands
	  *
	  * For example Icelandic uses `[',', '.']`
	  *
	  * Default: `['.', '']`
	  */
	splitters?: [string, string] | [string];
	// Supported by TS 4.0 https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-rc/#labeled-tuple-elements
	// splitters?: [decimal: string, thousands: string] | [decimal: string];
}

export const prettyNum = (number = 0, opts: PrettyNumOptions) => {
	const {
		decimals = 0, // is this the right default?
		fixedDecimals,
		lang = 'en',
		splitters = i18n[lang] || [],
	} = opts;

	const dSep = splitters[0] || '.';
	const tSep = splitters[1] || '';
```

...með fyrirvara um að þetta er skrifað beint inn í GitHub textarea box. 😁

2020-09-03 09:48 UTC, maranomynet commented on src/utils/prettyNum.tests.ts
> +		o(prettyNum(123456.789, 2, '.', ',')).equals('123.456,79');
Vantar að skjala hvað gerist þegar input gildið er með færri decimals en arg2 tilgreinir..

```suggestion
		o(prettyNum(123456.789, 2, '.', ',')).equals('123.456,79');
		// þetta? (max-decumals)
		o(prettyNum(123456.7, 2, '.', ',')).equals('123.456,7');
		o(prettyNum(123456, 2, '.', ',')).equals('123.456');
		// eða þetta? (fixed decimals)
		o(prettyNum(123456.7, 2, '.', ',')).equals('123.456,70');
		o(prettyNum(123456, 2, '.', ',')).equals('123.456,00');
```

Ég held að max-decimals sé almennt betra default.
En fixed-decimals sé nauðsynleg optional hegðun (sjá comment við `prettyNum.ts` að neðan)

2020-09-03 09:56 UTC, maranomynet commented on src/utils/prettyNum.tests.ts
> +		o(prettyNum(123456789)).equals('123.456.789');
Jafnframt: Hvað á að gerast þegar ég sendi inn weird ass broken float.

```js
o(prettyNum(1 - 0.7, 4)).equals('0.30000000000000004'); // <-- þetta?
o(prettyNum(1 - 0.7, 4)).equals('0.3000'); // <-- eða þetta?
o(prettyNum(1 - 0.7, 4)).equals('0.3'); // <-- eða þetta?
```

Þetta tengist líka "max-decimals" vs. "fixed-decimals" hegðunar pælingunum.

2020-09-03 17:54 UTC, Valur commented on src/utils/prettyNum.tests.ts
> +		o(prettyNum(123456789)).equals('123.456.789');
Þetta er allt komið

2020-09-03 20:25 UTC, Valur commented on src/utils/prettyNum.tests.ts
> +		o(prettyNum(123456.789, 2, '.', ',')).equals('123.456,79');
Búinn að innleiða fixed decimals

2020-09-03 20:25 UTC, Valur commented on src/utils/prettyNum.tests.ts
> +		o(prettyNum(123456.789, 2, '', '')).equals('12345679');
Þetta er komið

2020-09-03 20:25 UTC, Valur commented on src/utils/prettyNum.tests.ts
> +	});
komin test fyrir mínus tölur

2020-09-03 20:26 UTC, Valur commented on src/utils/prettyNum.ts
> +export const prettyNum = (number = 0, decimals = 0, tSep = '.', dSep = ',') => {
Þetta refactor er komið inn

2020-09-04 09:37 UTC, maranomynet requested changes

2020-09-04 09:37 UTC, maranomynet commented on src/utils/prettyNum.ts
> +	const numFloat = parseFloat('' + number);
```suggestion

	const numFloat = typeof number !== 'number' ? parseFloat('' + number) : number;
```

Hraðara codepath fyrir `number`s

2020-09-04 09:37 UTC, maranomynet commented on src/utils/prettyNum.ts
> +		return 'error';
```suggestion
		if (typeof process != undefined && process.env.NODE_ENV !== 'production') {
			console.error("prettyNum can't format:", number);
		}
		return '';
```

Ef við ætlum ekki að springa á invalid input - þá skulum við bara skila snyrtilegum tómum streng ''.
Það er leiðinlegt að prenta sýnilegt `"NaN"` eða `"error"` út í viðmótið.

Ég er pínu á báðum áttum hvort svona fall eigi að vera að logga villur.
En ef við gerum það held ég við ættum að láta þann kóða hverfa í production.

2020-09-04 09:37 UTC, maranomynet commented on src/utils/prettyNum.ts
> +	const re = new RegExp(`\\.\\d{${decimals}}`);
```suggestion
	const re =  reCache[decimals] || (reCache[decimals] = (new RegExp(`\\.\\d{${decimals}}`));
```

2020-09-04 09:37 UTC, maranomynet commented on src/utils/prettyNum.ts
> +
```suggestion

const reCache: Array<RegExp> = [];
```

2020-09-04 09:37 UTC, maranomynet commented on src/utils/prettyNum.tests.ts
> +		o(prettyNum('42', { decimals: 2, fixedDecimals: true })).equals('42.00');
```suggestion
		o(prettyNum('42', { decimals: 2, fixedDecimals: true })).equals('42.00')('fixed decimals appended to integer');
		o(() => prettyNum('42', true)).throws(Error)('invalid options');
```

2020-09-04 11:03 UTC, merged